/// HIVE TYPES
const int HIVE_TYPE_ID_BOOK_VO = 1;
const int HIVE_TYPE_ID_BUY_LINKS_VO = 2;
const int HIVE_TYPE_ID_MAIN_LIST_VO = 3;
const int HIVE_TYPE_ID_RESULTS_VO = 4;

const int HIVE_TYPE_ID_SHELF_V0 = 5;

const int HIVE_TYPE_ID_GENRE_VO = 6;
const int HIVE_TYPE_ID_MOVIE_VO = 7;
const int HIVE_TYPE_ID_PRODUCTION_COMPANY_VO = 8;
const int HIVE_TYPE_ID_PRODUCTION_COUNTRY_VO = 9;
const int HIVE_TYPE_ID_SPOKEN_LANGUAGE_VO = 10;

/// Box names
const String BOX_NAME_BOOK_VO = "BOX_NAME_BOOK_VO";
const String BOX_NAME_BUY_LINKS_VO = "BOX_NAME_BUY_LINKS_VO";
const String BOX_NAME_MAIN_LIST_VO = "BOX_NAME_MAIN_LIST_VO";
const String BOX_NAME_RESULTS_VO = "BOX_NAME_RESULTS_VO";

const String BOX_NAME_SHELF_VO = "BOX_NAME_SHELF_VO";

const String BOX_NAME_GENRE_VO = "BOX_NAME_GENRE_VO";
const String BOX_NAME_MOVIE_VO = "BOX_NAME_MOVIE_VO";
const String BOX_NAME_PRODUCTION_COMPANY_VO = "BOX_NAME_PRODUCTION_COMPANY_VO";
const String BOX_NAME_PRODUCTION_COUNTRY_VO = "BOX_NAME_PRODUCTION_COUNTRY_VO";
const String BOX_NAME_SPOKEN_LANGUAGE_VO = "BOX_NAME_SPOKEN_LANGUAGE_VO";

const String BOX_NAME_DATABASE_BOOK_LIST = "BOX_NAME_DATABASE_BOOK_LIST";